

test_task:
  name: Test macOS arm64 installed via pip.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode

  env:
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH

  setup_script:
    - brew install python@3.10
    - python --version
    - python -m pip install loristrck sndfileio

  test_script:
    - cd test
    - python ./test-stretch.py --outfile test-stretch-macos-arm64.wav

