container:
  image: python:latest

build_task_p310:
  name: Build macOS arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode

  env:
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    CIBW_BUILD: 'cp39-* cp310-* cp311-*'
    # We don't build for arm because the fftw lib is still not included
    CIBW_ARCHS_MACOS: arm64
    CIBW_SKIP: 'pp* *686* *-musllinux_*'
    CIBW_BEFORE_ALL_MACOS: brew update; brew install fftw
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}

  install_pre_requirements_script:
    #- brew install python@3.10
    #- ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
    - brew install fftw
  <<: *BUILD_AND_STORE_WHEELS

