build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  cibuildwheel_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python3 -m pip install cibuildwheel==2.16.5
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

macos_arm64_task:
  name: Build macOS arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode

  env:
    # PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    CIBW_BUILD: 'cp39-* cp310-* cp311-* cp312-*'
    CIBW_ARCHS_MACOS: 'arm64'
    # CIBW_ARCHS_MACOS: x86_64 arm64
    CIBW_SKIP: 'pp* *686* *-musllinux_*'
    CIBW_BEFORE_ALL_MACOS: brew install fftw
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
    TWINE_USERNAME: __token__
    # twine24.4, encrypted by cirrus at the repo level, it is only valid for this repository
    TWINE_PASSWORD: ENCRYPTED[e00ba740bee1f98bb9a7abade7bf0bd5cf98df2340f40f1b6e960c8b250280864d7fd4f4e079b8d5ca60065bdc7ea1ea]
    
  install_pre_requirements_script:
    - brew install python3
    # - ln -s python /opt/homebrew/opt/python@3.10/bin/python
  <<: *BUILD_AND_STORE_WHEELS

  upload_wheels_script:
    - echo "$TWINE_USERNAME"
    - echo "$TWINE_PASSWORD"
    - source .venv/bin/activate
    - python3 -m pip install -U twine virtualenv
    - python3 -m twine upload --skip-existing wheelhouse/*.whl


test_task:
  name: Test macOS arm64 installed via pip.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode

  env:
    PATH: /opt/homebrew/opt/python@3.10/libexec/bin:$PATH

  test_script:
    - brew install python3   # at the moment this installs 3.12
    - python3 -m venv .test
    - source .test/bin/activate
    - python3 --version
    - python3 -m pip install loristrck sndfileio
    - cd test
    - python3 ./test-stretch.py --outfile test-stretch-macos-arm64.wav
    - ls -l testout

  testout_artifacts:
    path: test/testout/*

