build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.16.5
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

macos_arm64_task:
  name: Build macOS arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode

  env:
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    CIBW_BUILD: 'cp39-* cp310-* cp311-*'
    CIBW_ARCHS_MACOS: 'arm64'
    # CIBW_ARCHS_MACOS: x86_64 arm64
    CIBW_SKIP: 'pp* *686* *-musllinux_*'
    CIBW_BEFORE_ALL_MACOS: brew install fftw
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}

  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  <<: *BUILD_AND_STORE_WHEELS


test_task:
  name: Test macOS arm64 installed via pip.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode

  env:
    PATH: /opt/homebrew/opt/python@3.10/libexec/bin:$PATH

  setup_script:
    - brew install python@3.10
    - python --version
    - python -m pip install loristrck sndfileio

  test_script:
    - cd test
    - python ./test-stretch.py --outfile test-stretch-macos-arm64.wav

