site_name: loristrck
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections

extra_css:
  - stylesheets/extra.css
      
markdown_extensions:
    - toc:
        toc_depth: 2
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition

use_directory_urls: false

repo_url: https://github.com/gesellkammer/loristrck

nav:
    - index.md 
    - reference.md
    - util.md
    - commandline.md