site_name: loristrck
theme:
    name: material
    features:
        - navigation.tabs
    
markdown_extensions:
    - toc
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition

use_directory_urls: false
