name: Python package build and publish

on:
  create
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
      with:
        python-versions: 'cp38-cp38m cp39-cp39m'
        build-requirements: 'cython numpy'
        system-packages: 'fftw-devel libsndfile-devel'
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: Eduardo.Moguillansky
        TWINE_PASSWORD: ${{ secrets.pypipass }}
      run: |
        twine upload --skip-existing dist/*-manylinux*.whl
