name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
# Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    # python scripts/prepare_windows_build.py

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build Loris
        run: |
          python scripts/prepare_windows_build.py









