name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
# Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    # python scripts/prepare_windows_build.py


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # install Visual Studio 2022 Community
      - name: Install Visual Studio 2022 
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64


      - name: Build Loris
        run: |
          Write-Output "Current Location is $($PWD.Path)"
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          powershell  -NoExit -Command "Import-Module ./Common7/Tools/Microsoft.VisualStudio.DevShell.dll; Enter-VsDevShell d718e166 -SkipAutomaticLocation"
          cd ${{github.workspace}}
          python scripts/prepare_windows_build.py

      - name: Build wheels
        run: |
          python -m pip install wheel
          python setup.py bdist_wheel







