name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
# Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      # Use python3.11
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Visual Studio Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        # Go to a Developer Command Prompt
        run: |
            python scripts/prepare_windows_build.py
            dir




