name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
# Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: Windows-latest
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # install Visual Studio 2022 Community
      - name: Install Visual Studio 2022 
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Loris
        run: |
          Write-Output "Current Location is $($PWD.Path)"
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          powershell  -NoExit -Command "Import-Module ./Common7/Tools/Microsoft.VisualStudio.DevShell.dll; Enter-VsDevShell d718e166 -SkipAutomaticLocation"
          cd ${{github.workspace}}
          python scripts/prepare_windows_build.py

      - name: Build wheels
        run: |
          python -m pip install wheel
          python setup.py bdist_wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl

# Make Linux build
  Linux_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
            # if linux, install fftw  
      - name: Install fftw for Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libfftw3-dev
      
      # if macos, install fftw
      - name: Install fftw for MacOS
        if: matrix.os == 'macOS-11'
        run: brew install fftw

      - name: Build wheels
        run: |
          python -m pip install wheel
          python setup.py bdist_wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl







