name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
# Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      # Use python3.11
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run in Developer Powershell
        # run in Developer Powershell"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
        - uses: ilammy/msvc-dev-cmd@v1
        - name: Build Loris
          run: |
            python scripts/prepare_windows_build.py





