name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-10.15, windows-2019]
        os: [macOS-10.15]
        # os: [ubuntu-20.04]
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies macos
        if: runner.os == 'macos'
        run: |
            brew install fftw
            brew install libsndfile

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0 twine virtualenv numpy cython

      - name: Build wheels
        run: |
            # python setup.py build_ext
            python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      - name: Upload wheels
        env:
          #TWINE_USERNAME: __token__
          TWINE_USERNAME: Eduardo.Moguillansky
          #TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_PASSWORD: ${{ secrets.pypipass }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            twine upload --skip-existing wheelhouse/*.whl
        continue-on-error: true