name: Build

on: [push, pull_request]

jobs:
  # Make Windows build
  Windows_build_wheels:
    name: Build python wheels on ${{ matrix.os }}
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Build Loris
        run: |
          python scripts/prepare_windows_build.py

      - name: Build wheels
        run: |
          python -m pip install --upgrade pip wheel numpy setuptools cython
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ strategy.job-index }}
          path: dist/*.whl

      - name: Upload wheels
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINETOKEN }}
        run: |
          python -m pip install twine
          twine upload --skip-existing dist/*.whl

  build_wheels:
    name: Build python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel twine

      - name: Build wheels
        env:
          MACOSX_DEPLOYMENT_TARGET: 14.0
          CIBW_BUILD: 'cp310-* cp311-* cp312-* cp313-*'
          CIBW_SKIP: 'pp* *686* *-musllinux_*'
          CIBW_BUILD_VERBOSITY: 2
          CIBW_BEFORE_ALL_LINUX: yum install -y fftw-devel
          CIBW_BEFORE_ALL_MACOS: brew update; brew install fftw
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Upload wheels
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINETOKEN }}
        run: |
          twine upload --skip-existing wheelhouse/*.whl
